
["Lazy Utilities - Modules -/- Main"]
	#Determine how Lazy Utilities Main Module will handle errors.
	#
	#CATCH: Catches errors, preventing the game from closing if an error occurs. It does not provide any debugging data.
	#
	#EXCEPTION: Closes the game immediately upon an error. The closure is immediate and provides debugging data.
	#Allowed Values: CATCH, EXCEPTION
	fatalLazyUtilitiesRuntimeHandler = "CATCH"

["Lazy Utilities - Modules -/- Epic Fight"]
	#Determine how the Epic Fight module (LZM: Epic Fight) will handle errors.
	#
	#CATCH: Catches errors, preventing the game from closing if an error occurs. It does not provide any debugging data.
	#
	#EXCEPTION: Closes the game immediately upon an error. The closure is immediate and provides debugging data.
	#Allowed Values: CATCH, EXCEPTION
	fatalEpicFightRuntimeHandler = "CATCH"

["Lazy Utilities - Modules -/- Better Combat"]
	#Determine how the Better Combat (LZM: Better Combat) module will handle errors.
	#
	#CATCH: Catches errors, preventing the game from closing if an error occurs. It does not provide any debugging data.
	#
	#EXCEPTION: Closes the game immediately upon an error. The closure is immediate and provides debugging data.
	#Allowed Values: CATCH, EXCEPTION
	fatalBetterCombatRuntimeHandler = "CATCH"

